### ISSUE TITLE
Fatal Compile Error: Declaration of Http\Client\Socket\Stream::close() must be compatible

### ISSUE THREAD

**Issue by Rid** [beluga-php/docker-php-api#14]
Unless I use `"psr/http-message": "1.1"` in composer.json, I get the error:

`Declaration of Http\Client\Socket\Stream::close() must be compatible`

Looks related to: https://github.com/php-http/socket-client/pull/69

Can anyone reproduce? If so we might need to update our `composer.json`

**Comment by flavioheleno** [comment]
Got to reproduce the error.

By reading the issue and related discussions, we may need to replace `php-http/socket-client` with relevant PSR interfaces - at least PSR18 -, and suggest one or more implementations.

**Comment by Rid** [comment]
I'm personally already using https://github.com/guzzle/guzzle which also has socket support.

Are there any other suggestions?

**Comment by flavioheleno** [comment]
I'd suggest Guzzle as well and maybe `symfony/http-client`, but any of the [packages that provide](https://packagist.org/providers/psr/http-client-implementation) `psr/http-client-implementation` should be ok as long as they provide unix socket support.

Shall we move with this:

in `docker-php-api`:
1. Remove `nyholm/psr7` under `require`;
2. Remove `php-http/socket-client` under `suggest`
3. Add `psr/http-client-implementation` under `require`;
4. Add `psr/http-factory-implementation` under `require`;
5. Add `psr/http-message-implementation` under `require`.

in `docker-php`:
1. Replace `php-http/socket-client` with `psr/http-client-implementation`;
6. Remove `php-http/client-common`;
7. Replace `nyholm/psr7` with `psr/http-message-implementation`;
8. Remove `php-http/httplug-bundle` under `suggest`;
9. Add `guzzlehttp/guzzle` under `suggest`.

Those changes will leave the actual implementation of the underlying transport (HTTP) to the project using `docker-php` and `docker-php-api` and no longer force any packages, but suggest `guzzlehttp/guzzle` as a viable implementation.

**Comment by Rid** [comment]
@flavioheleno All looks good to me 👍

**Comment by flavioheleno** [comment]
Done in [beluga-php/docker-php#6c0fcd4](https://github.com/beluga-php/docker-php/commit/6c0fcd4f0501c277aa412f8047b550da224aa649) and [beluga-php/docker-php-api#8a95e39](https://github.com/beluga-php/docker-php-api/commit/8a95e391cf5b8a7f2e152ed7b8152c31750e0ac3)
