### ISSUE TITLE
Exposed ports is array when should be object

### ISSUE THREAD

**Issue by Rid** [beluga-php/docker-php-api#6]
Currently investigating this:

https://github.com/beluga-php/docker-php-api/blob/0082dac1f074aa56abe82d6f18aebb5823559921/src/Normalizer/ContainersCreatePostBodyNormalizer.php#L245-L251

As it causes a `Error ContainerCreateInternalServerErrorException: json: cannot unmarshal array into Go struct field ContainerConfigWrapper.ExposedPorts of type struct {}` error because the generated json is:

`"ExposedPorts":{"10012/tcp":[],"80/tcp":[]}`

When it should be

`"ExposedPorts":{"10012/tcp":[],"80/tcp":{}}`

The swagger is 

```
          "ExposedPorts": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {}
            },
            "description": "An object mapping ports to an empty object in the form:\n\n`{\"<port>/<tcp|udp|sctp>\": {}}`\n"
          },
```

So I'm not sure why janephp isn't generating this as the same as the denormalizer?

https://github.com/beluga-php/docker-php-api/blob/0082dac1f074aa56abe82d6f18aebb5823559921/src/Normalizer/ContainersCreatePostBodyNormalizer.php#L80-L85

I'll open an issue with janephp if needed, just checking if you've already spotted this?

**Comment by Rid** [comment]
Opened an issue here https://github.com/janephp/janephp/issues/700

**Comment by flavioheleno** [comment]
hey @Rid thank you very much for your help all around! let's take the dust off of this project and make it work properly!
I'm currently looking at some alternatives for having minor patches to fix such issues in this repository (prior to tagging a version), while support from Jane is in the works (same goes for other issues).
What do you think?

**Comment by Rid** [comment]
@flavioheleno I have a version working locally, only #3 and this issue need to be patched manually in the generated code (although I haven't tested every API endpoint). Do you want me to make a PR with the needed client changes?

**Comment by flavioheleno** [comment]
I'd like to have those changes as `.patch` files in a folder, so when we run the build step, they get applied before running the lint, so that they don't get lost between updates.
Can you start a PR with those patches on a dedicated folder while I work the automation?

**Comment by Rid** [comment]
@flavioheleno I've made a PR, I've also added automation via composer for applying the patches

**Comment by Rid** [comment]
Looking at the API reference we're going to need a few more patches, basically anywhere we return an object we need to initialise it with

```php
$values = new \ArrayObject([], \ArrayObject::ARRAY_AS_PROPS);
```

As if the object is empty, it will return an empty array, this is the same for parent objects and nested.

I'll go through the API in a few days and add the patch where needed and update the patch set.

**Comment by Rid** [comment]
Is it possible for you to add me to the repository so I can commit directly?

**Comment by Rid** [comment]
I've submitted a PR upstream at https://github.com/janephp/janephp/pull/703

I'll use that to generate a new PR here.
